name = "NiaARM"
uuid = "cb655f37-3f9a-467f-922e-5a165e048db7"
version = "0.3.0"
authors = ["Žiga Stupan <ziga.stupan1@student.um.si>", "Tilen Hliš <tilen.hlis@proton.me>", "Iztok Fister Jr. <iztok@iztok-jr-fister.eu>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CSV = "0.10.15"
CategoricalArrays = "1.0.2"
DataFrames = "1.8.1"
Random = "1.11.0"
SpecialFunctions = "2.6.1"
julia = "1.12"

[workspace]
projects=["docs", "test"]
