name = "NumAssociationRules"
uuid = "cb655f37-3f9a-467f-922e-5a165e048db7"
authors = ["Iztok Fister Jr. <iztok@iztok-jr-fister.eu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
